name: Wake up Render App

on:
  schedule:
    - cron: '40 12 * * *'   # 09:40 São Paulo (12:40 UTC)
    - cron: '40 17 * * *'   # 14:40 São Paulo (17:40 UTC)

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm install socket.io-client

      - name: Run wakeup script
        run: node wakeup.js
